### ISSUE TITLE
[bug]: 获取稿件经常出错

### ISSUE THREAD

**Issue by oyer** [catlair/BiliOutils#199]
### 是否已经阅读文档

- [X] 我确定阅读过文档

### 运行环境和版本

青龙面板v2.15.10

### 发生了什么

经常获取不到稿件

### 相关的日志输出

```shell
[👻 12:05:53] ----【每日投币】----
[👻 12:05:53] 投币数量：0，还需投币数量: 5颗;(目标5颗)
[🐛 12:06:03] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:06:15] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:06:26] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:06:37] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:06:50] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:06:55] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:07:02] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:07:11] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:07:22] 获取稿件错误：请求过于频繁，请稍后再试
[🐛 12:07:30] 获取稿件错误：请求过于频繁，请稍后再试
[❔ 12:07:30] 获取稿件错误次数超过 10 次，自动退出投币
```

**Comment by KudouRan** [comment]
这个日志看不出来具体的问题，两周前我更新了这部分代码的日志

![图片](https://github.com/catlair/BiliOutils/assets/81743795/3b22f78c-c4f0-4dcd-87b2-ade220bc63f1)

所以希望能够更新到最新后重新获取日志，以便定位问题。

**Comment by oyer** [comment]
青龙面板v2.15.10
bilioutils v0.23.803
配置
![image](https://github.com/catlair/BiliOutils/assets/114124689/9edca105-d4ad-4b68-bd58-2f6be52e9933)

**Comment by KudouRan** [comment]
好的，请尝试 v0.23.804

**Comment by catlair** [comment]
如果可以的话可以关闭 issue

**Comment by oyer** [comment]
测试了，没报错了。
1. 但我发现配置中解除投币5个限制的配置好像没作用。就上面那个配置应该投币是10个，但实际上还是投的5个
```
[👻 12:17:24] ----【每日投币】----
[👻 12:17:24] 投币数量：4，还需投币数量: 1颗;(目标5颗)
```
2. 还有那个投币相关的配置，我设置了指定up主投币但还是会根据顺序给其他up主投币。这有点不符合预期，我需求是如果自定义up主的用户组似乎没有币可投了就跳过投币。（这个我可以自己改了提交pr）
