### ISSUE TITLE
指定up主投币但还是会根据顺序给其他up主投币

### ISSUE THREAD

**Issue by catlair** [catlair/BiliOutils#200]
2. 还有那个投币相关的配置，我设置了指定up主投币但还是会根据顺序给其他up主投币。这有点不符合预期，我需求是如果自定义up主的用户组似乎没有币可投了就跳过投币。（这个我可以自己改了提交pr）

_Originally posted by @oyer in https://github.com/catlair/BiliOutils/issues/199#issuecomment-1666385386_

**Comment by catlair** [comment]
@oyer 在配置中是有 src 这个配置的

```json5
{
 coin: {
    /** 自定义高优先级用户列表 */
    customizeUp: [] as number[],
    /** 目标等级 默认6级 */
    targetLevel: 6,
    /** 最低剩余硬币数,默认0 */
    stayCoins: 0,
    /** 预计投币数,默认5 */
    targetCoins: 5,
    /** 稿件必须是 up 的稿件，而非合作视频中的参与者 */
    upperAccMatch: false,
    /** 获取稿件的来源（排序），留空则来自 首页推荐 */
    src: ['自定义UP', '特别关注', '关注', '首页推荐', '分区排行'],
  }
}
```

不过实际测试发现当时是写了 ` idFunc?.(types && types.map(el => TypeEnum[el])) || getAidByRecommend();`  这样一个兜底的操作，这应该是多余的，去掉后就能达到这个效果了。

不知道你的想法是什么，或者就这样也可以

**Comment by oyer** [comment]
我的需求应该只有我要用到，我用别人的站号登录然后批量给自己投币刷经验。就是用别人有较多硬币的号扫码登录，给我所有的视频，专栏等投币

这个地方兜底应该没问题，我感觉像是getRandmonNum那个函数取值越界导致触发兜底。

东西太多逻辑还没理通0.0，我再看看吧

**Comment by catlair** [comment]
你理解错了。getRandmonNum 是获取 up 主的投稿的，在配置 upperAccMatch 后不可能获取到其他 up 的。

**Comment by catlair** [comment]
应该没有问题了，把限制那个修修
