### ISSUE TITLE
[青龙面板]请问下青龙安装依赖bilioutils失败是啥原因 

### ISSUE THREAD

**Issue by wph1773** [catlair/BiliOutils#207]
### 是否已经阅读文档

- [X] 我确定阅读过文档

### 运行环境和版本

青龙2.11.3

### 发生了什么

青龙安装依赖bilioutils失败

**Comment by catlair** [comment]
无法安装与本项目无关，系青龙面板的问题。你可以尝试安装axios got dayjs等包，查看是否能够安装其他包
