### ISSUE TITLE
[请求]: 那个扫码登录的库`@catlair/blogin`能开源吗

### ISSUE THREAD

**Issue by xqa** [catlair/BiliOutils#217]
### 需求描述

我想自己写点东西，需要用到扫码登录获取cookie，但我看源码使用的是@catlair/blogin这个库，但并没有开源。
虽然[SocialSisterYi/bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect)有，但还是想看看你的学习一下（就是懒，想cv来用 :smile: ）

### 有效的帮助

这个接口是这样的。。。

**Comment by catlair** [comment]
https://github.com/catlair/node-blogin

**Comment by xqa** [comment]
谢谢大佬:star_struck:
