### ISSUE TITLE
[Bug]: 网络获取活动列表报错

### ISSUE THREAD

**Issue by vay1314** [catlair/BiliOutils#234]
### 运行环境和版本

linux ，当前版本【v0.23.1022】

### 发生了什么

网络获取活动列表报错，提示All promises were rejected

### 预期的结果

能否修复

### 相关的日志输出

[💬 08:09:35]  通过网络获取活动列表
[❓ 08:09:41]   All promises were rejected

**Comment by catlair** [comment]
当前可以直接在 配置里把 github 的代理更换一下，详见https://mirror.ghproxy.com/

**Comment by catlair** [comment]
![image](https://github.com/catlair/BiliOutils/assets/44313800/608159d9-79cc-4ddc-90b4-750c416e16d9)

**Comment by vay1314** [comment]
好的

**Comment by catlair** [comment]
v0.23.1115 对获取逻辑进行了优化
