### ISSUE TITLE
[Bug]: 天选红包报错

### ISSUE THREAD

**Issue by yukiryo** [catlair/BiliOutils#236]
### 运行环境和版本

青龙面板2.16.5

### 发生了什么

天选时刻异常

### 相关的日志输出

```shell
[👻 11:41:29]  ----【天选红包】----
[❔ 11:41:32]  天选时刻异常: areas is not iterable
[🐛 11:41:32]  TypeError: areas is not iterable
[👻 11:41:32]  结束天选红包
```

**Comment by catlair** [comment]
![image](https://github.com/catlair/BiliOutils/assets/44313800/f9bbd2f8-dbd8-4e5e-8211-1450edb50708)

**Comment by catlair** [comment]
发现现在的逻辑有点问题，以后再看吧
