### ISSUE TITLE
[Bug]: 天选红包扫描次数配置不生效

### ISSUE THREAD

**Issue by Astlm** [catlair/BiliOutils#242]
### 运行环境和版本

iStoreOS 22.03.6 2024012613
docker V20.10.22

### 发生了什么

循环依然存在
![Screenshot_2024-02-01-21-29-28-323_com kiwibrowser browser](https://github.com/catlair/BiliOutils/assets/106404630/901b6b81-ce86-4155-b0c8-3ee3b81dd17c)

### 相关的配置，注意个人隐私。

```json
"redPack": {
      "source": 2,
      "restTime": [
        1,
        1
      ],
      "riskTime": [
        2,
        2
      ],
      "totalNum": 30,
      "scanAreaTimes": 1
    },
```

**Comment by catlair** [comment]
收到，有空的时候再看看

**Comment by catlair** [comment]
已修复，但是红包目前存在未知反爬策略，并不一定能够成功获取到数据
