### ISSUE TITLE
[Bug]: 利用/usr/bin/docker pull catlair/bilitools:latest无法更新到1.1.4

### ISSUE THREAD

**Issue by ZeroMah** [catlair/BiliOutils#246]
### 运行环境和版本

Ubuntu docker

### 发生了什么

利用/usr/bin/docker pull catlair/bilitools:latest无法更新到1.1.4， 请问一下如何解决
![image](https://github.com/catlair/BiliOutils/assets/63148494/503dd630-bccd-40ba-8854-1a0bdbec87d7)

**Comment by catlair** [comment]
catlair/bilitools 为历史遗留镜像，使用的是 npm @catlair/bilitools , 最新版本为1.0.2（停更1年）
catlair/bilioutils 使用的才是 bilioutils，最新版本 1.1.4
