### ISSUE TITLE
[Bug]: 6007000 请将客户端更新至最新版本

### ISSUE THREAD

**Issue by D10NGYANG** [catlair/BiliOutils#251]
### 运行环境和版本

青龙面板2.16.5

### 发生了什么

 【Err】Bili-R**够-每日完成

[👻 12:12:22] 当前版本【v1.2.0】
[💬 12:12:26] 本项目开源且免费，文档地址 https://bo.js.cool 使用请自觉 star，by --- catlair。
[👻 12:12:26] ----【登录】----
[👻 12:12:32] 登录成功: Rep唔够
[👻 12:12:32] 硬币余额: 1352.3
[👻 12:12:32] 当前等级: 6
[👻 12:12:32] 已经满级（关闭部分功能）
[👻 12:12:32] 大会员状态: 年度大会员
[👻 12:12:32] ----【直播签到】----
[👻 12:12:35] 直播签到成功: 3000点用户经验,2根辣条，特别信息: ，本月签到天数: 27天;
[👻 12:12:35] ----【大会员积分】----
[👻 12:12:38] 当前积分: 5885
[❓ 12:12:42] 领取任务undefined失败: 6007000 请将客户端更新至最新版本
[❓ 12:12:47] 今日获取积分【35】, 未达到预期 ×
[❓ 12:13:08] 领取任务undefined失败: 6007000 请将客户端更新至最新版本
[❓ 12:13:11] 今日获取积分【35】, 未达到预期 ×
[❓ 12:13:34] 领取任务undefined失败: 6007000 请将客户端更新至最新版本
[👻 12:13:37] ----【银瓜子兑换硬币】----
[👻 12:13:38] 兑换失败，你瓜子不够了
[👻 12:13:38] ----【领取大会员权益】----
[👻 12:13:38] 暂无可领取权益（除保留）
[👻 12:13:38] ----【使用b币券】----
[👻 12:13:38] 不在预设时间，不符合条件
[👻 12:13:39] ----【大会员领取经验】----
[👻 12:13:40] 获取经验成功

**Comment by catlair** [comment]
观看视频接口变更，逻辑也变了，需要分析新的逻辑

**Comment by catlair** [comment]
值得注意的是，现在需要实际消耗10分钟
