### ISSUE TITLE
大会员视频观看任务似乎需要更新？ 

### ISSUE THREAD

**Issue by ypq123456789** [catlair/BiliOutils#257]
### 运行环境和版本

腾讯云函数

### 发生了什么

配置都没啥问题，大会员视频观看任务无法成功，可能是因为大会员现在变成只能手机端app看了，看10分钟+40大积分

**Comment by catlair** [comment]
#251 重复问题，提issue前未阅读须知

**Comment by catlair** [comment]
云函数默认不启用异步，为适配云函数可以将配置bigPoint.isAsyncWatch改为false，变为同步执行，这将会导致云函数等待10分钟

**Comment by ypq123456789** [comment]
> 云函数默认不启用异步，为适配云函数可以将配置bigPoint.isAsyncWatch改为false，变为同步执行，这将会导致云函数等待10分钟

感谢我试一试，谢谢谢谢

**Comment by ypq123456789** [comment]
大佬，好像没看到bigpoints里面有isAsyncWatch这个参数啊，我手动加上去也是红色的，好像报错了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 中午11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [catlair/BiliOutils] 大会员视频观看任务似乎需要更新？  (Issue #257)




 
云函数默认不启用异步，为适配云函数可以将配置bigPoint.isAsyncWatch改为false，变为同步执行，这将会导致云函数等待10分钟

**Comment by catlair** [comment]
有没有他也不可能报错，那是你自己写错了格式。

**Comment by catlair** [comment]
https://github.com/catlair/BiliOutils/commit/7539c1f4b855a8c2070ee3d7260684e1dd1a02d8#

**Comment by catlair** [comment]
文档已更新
