### ISSUE TITLE
[提示]: 不会添加的功能，如有需要请查看

### ISSUE THREAD

**Issue by KudouRan** [catlair/BiliOutils#94]
### 需求描述

由于种种原因，目前只修 bug 和维护已有功能，不想要添加新功能，如果你有以下需求，可以在此留言，然后右上角关闭。

- 活动抽奖
- 动态抽奖
- 其他未包含但已有项目存在的功能。

**Comment by wdssfff00** [comment]
**功能：转盘抽奖**
想法：
每天主动抓取转发抽奖娘转发的链接，并自动解析转盘。

（爬虫方面没什么经验，候补方案是）
手动填写转盘链接到配置，感兴趣的人自己手动填然后转盘
当然也可以人性化自动抓取和人工紧急添加结合。。。。

参考实例：https://github.com/silie666/bilibiliLottery

**Comment by catlair** [comment]
> **功能：转盘抽奖** 想法： 每天主动抓取转发抽奖娘转发的链接，并自动解析转盘。
> 
> （爬虫方面没什么经验，候补方案是） 手动填写转盘链接到配置，感兴趣的人自己手动填然后转盘 当然也可以人性化自动抓取和人工紧急添加结合。。。。
> 
> 参考实例：https://github.com/silie666/bilibiliLottery

代码已经包含了，如有需要从源码运行
